"use client";

import { darkTheme, lightTheme } from "@/styles/theme";
import { ChangeEvent, useState } from "react";
import {
    ThemeProvider,
    CssBaseline,
    Switch,
    FormControlLabel,
    Grid,
    Typography,
    Button,
    ButtonGroup,
} from "@mui/material";

export default function Layout({ children }: { children: React.ReactNode }) {
    let [useDarkTheme, setUseDarkTheme] = useState(true);
    let [theme, setTheme] = useState(useDarkTheme ? darkTheme : lightTheme);

    const changeThemeHandler = (target: ChangeEvent, currentValue: boolean) => {
        setUseDarkTheme(currentValue);
        setTheme(currentValue ? darkTheme : lightTheme);
    };

    return (
        <html lang="en">
            <head>
                <title>Create Next App</title>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <ThemeProvider theme={theme}>
                <CssBaseline />
                <body id="__next">
                    <Grid
                        container
                        alignItems={"center"}
                        justifyContent={"space-between"}
                        rowGap={2}
                        padding={2}
                    >
                        <Grid xs={4} item={true}>
                            <Typography variant="h2">Logo</Typography>
                        </Grid>
                        <Grid
                            xs={8}
                            container
                            item={true}
                            gap={1}
                            justifyContent={"flex-end"}
                        >
                            <Button size="large">Login</Button>
                            <Button size="large" variant="outlined">
                                Sign up
                            </Button>
                        </Grid>
                    </Grid>
                    {children}
                </body>
            </ThemeProvider>
        </html>
    );
}
